// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using payapp.data.Models;

namespace payapp.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210227191227_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("payapp.data.Models.ClientOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnName("client_id")
                        .HasColumnType("uuid");

                    b.Property<int>("OperationType")
                        .HasColumnName("operation_type")
                        .HasColumnType("integer");

                    b.Property<decimal>("OperationValue")
                        .HasColumnName("operation_value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("client_operations");
                });
#pragma warning restore 612, 618
        }
    }
}
